buildscript {
    repositories {
        google()
        mavenCentral()
    }
    ext.kotlin_version = '1.9.24'
    dependencies {
        // Actualizamos al conector moderno 8.4.0 compatible con fusiones limpias
        classpath 'com.android.tools.build:gradle:8.4.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
