name: Compilar Tube APK Firmado

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Esto te activa el boton manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el codigo fuente
      uses: actions/checkout@v4

    - name: Configurar Entorno Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Crear archivos de inicio de Gradle si no existen
      run: |
        if [ ! -f gradlew ]; then
          gradle wrapper --gradle-version 8.2 --distribution-type bin
        fi
        chmod +x ./gradlew

    - name: Compilar APK en modo Release
      run: ./gradlew assembleRelease --no-daemon

    - name: Generar clave y firmar el APK en la nube
      id: sign_app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY || 'MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBANMxMzU3OTI0NgIDAQAB' }}
        alias: 'tube_key'
        keyStorePassword: 'tubepassword123'
        keyPassword: 'tubepassword123'

    - name: Subir tu app Tube lista para instalar
      uses: actions/upload-artifact@v4
      with:
        name: Tube-Instalable-Sin-Anuncios
        path: ${{ steps.sign_app.outputs.signedReleaseFile }}
